# Generated by Django 4.2.23 on 2026-01-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_at',
        ),
    ]
