# Generated by Django 4.2.27 on 2026-01-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchsession',
            options={'ordering': ['start_datetime', 'session_number']},
        ),
        migrations.AddField(
            model_name='batchsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batchsession',
            name='session_number',
            field=models.PositiveIntegerField(default=1, help_text='Session number in the batch'),
        ),
        migrations.AlterUniqueTogether(
            name='batchsession',
            unique_together={('batch', 'session_number', 'start_datetime')},
        ),
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='lms.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='lms.batchsession')),
            ],
            options={
                'unique_together': {('enrollment', 'session')},
            },
        ),
    ]
