# Generated by Django 4.2.23 on 2026-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_qanda_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('physical', 'Physical Class'), ('internship', 'Internship'), ('bootcamp', 'Bootcamp')], default='physical', help_text='Type of batch: Physical Class, Internship, or Bootcamp', max_length=20),
        ),
    ]
