# Generated by Django 4.2.27 on 2026-01-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_add_batch_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
    ]
