# Generated by Django 4.2.23 on 2026-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_remove_note_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Featured image for course cards (preferred over thumbnail)'),
        ),
    ]
